name: regenerate hints and dist

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  regenerate-hints-and-dist:
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: regenerate hints and dist
        run: |
          # build the new artifacts (in ./result)
          nix build --no-write-lock-file .#hacl.passthru.build-products
          # delete the old ones
          git rm -r hints dist/*/*
          # copy the new artifacts
          tar -xvf result/hints.tar.gz
          tar -xvf result/dist.tar.gz

      - name: commit changes
        run: |
          git config --local user.name "Hacl Bot"
          git config --local user.email "hacl-star@mailo.com"
          git add hints dist
          git commit -m "[CI] regenerate hints and dist"

      - name: avoid trivial changes
        run: |
          [[ 1 -lt $(git diff --compact-summary HEAD~.. | grep -v INFO.txt | wc -l) ]]

      - name: leave no uncommitted changes
        run: |
          git restore .
          git clean -xfd

      - name: create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.HACL_BOT }}
          branch: "hints-and-dist-main"
          title: "[CI] regenerate hints and dist"
